services:
  - type: web
    name: depo-qr-tracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    branch: main
    runtime: python
